AWSTemplateFormatVersion: '2010-09-09'
Resources:
  prodEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0cca134ec43cf708f
      InstanceType: t2.micro
      KeyName: web-server